jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      name: Set up JDK 17
      with:
        java-version: '17'
        distribution: adopt
    - name: 'Hello: sayHello'
      run: echo "Hello, ${name}! This message is from the shared library."
    - name: 'Install Maven Dependencies: installMavenDependencies'
      run: mvn clean install
    - name: 'Build: buildProjectWithMaven'
      run: mvn clean package
    - name: 'Run Tests: runTestsWithMaven'
      run: mvn test
name: Jenkins to GitHub Actions
'on': push
